-- Intentionally contains no credentials or personal data.
-- Provision lenders through the application so otp_password is encrypted with
-- OTP_CREDENTIAL_ENCRYPTION_KEY. Never commit real lender IDs, mobile numbers,
-- mailbox addresses, app passwords, API keys, or production data.
